name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main] 
    types: [opened, synchronize] 
    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies in front
        run: npm install
        working-directory: frontend
        
      - name: Install dependencies in core
        run: npm install
        
      - name: Lint frontend 
        run: npm run lint
        working-directory: frontend
        
      - name: Lint core 
        run: npm run lint
        
      - name: Run Tests
        run: npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI}}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }} 
      
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Start server in the background
        run: npm run start:test &
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI}}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}    

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          working-directory: frontend
          wait-on: 'http://localhost:3000'
      - name: Trigger deployment
        if: github.event_name == 'push' && !contains(toJson(join(github.event.commits.*.message)), '#skip') 
        run: curl ${{ secrets.DEPLOY_URL }}
      - name: Deploy success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: Deploy has succeded ! 
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: BUILD FAILED!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}      
  tag_release:
      needs: [simple_deployment_pipeline]
      runs-on: ubuntu-20.04
      steps:
       - uses: actions/checkout@v3
         with:
          fetch-depth: '0'
       - name: Bump version and push tag
         if: github.event_name == 'push' && !contains(toJson(join(github.event.commits.*.message)), '#skip')  
         uses: anothrNick/github-tag-action@1.64.0 
         env: 
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            DEFAULT_BUMP: patch
             
      
          
